apiVersion: v1
kind: Service
metadata:
  name: node-hostname
  labels:
    app.kubernetes.io/name: node-hostname
    app.kubernetes.io/managed-by: argocd
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: node-hostname
  ports:
    - name: http
      port: 80
      targetPort: 8080
