apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-hostname
resources:
  - deployment.yaml
  - managedcertificate.yaml
  - ingress.yaml
images:
  - name: europe-west1-docker.pkg.dev/fiery-azimuth-470410-b6/nh-docker/node-hostname
    newTag: sha-5011a7fdbcd9 # CI will update this to the new image tag
