apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-hostname
resources:
  - ../common/namespace.yaml
  - ../common/service.yaml
  - ../common/argocd.yaml
  - deployment.yaml
  - managedcertificate.yaml
  - ingress.yaml
images:
  - name: europe-west1-docker.pkg.dev/fiery-azimuth-470410-b6/nh-docker/node-hostname
    newTag: sha-1e4f32ee35ce # CI will update this to the new image tag
